name: 'GitHub Pages action'
description: 'GitHub Actions for GitHub Pages 🚀 Deploy static files and publish your site easily. Static-Site-Generators-friendly.'
author: 'peaceiris'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  emptyCommits:
    description: 'If empty commits should be made to the publication branch'
    required: false
    default: 'true'
  keepFiles:
    description: 'If existing files in the publish branch should be not removed before deploying'
    required: false
    default: 'false'
  forceOrphan:
    description: 'Keep only the latest commit on a GitHub Pages branch'
    required: false
    default: 'false'
  username:
    description: 'Set Git user.name'
    required: false
  useremail:
    description: 'Set Git user.email'
    required: false
  commitMessage:
    description: 'Set custom commit message'
    required: false
  tagName:
    description: 'Set tag name'
    required: false
  tagMessage:
    description: 'Set tag message'
    required: false
  tagOverwrite:
    description: 'Enable overwriting tag'
    required: false
    default: false
