# File: .github/workflows/main.yml

name: Main Workflow

on:
  schedule:
     - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  first-job:
    uses: praveenjp12/cypress-project/.github/workflows/reusable-workflow.yml@main
    with:
      name: "Report1"
      runcommand: "npx cypress run --env allure=true --browser chrome"

  second-job:
    needs: first-job              # Wait for first-job
    if: always()        
    uses: praveenjp12/cypress-project/.github/workflows/reusable-workflow.yml@main
    with:
      name: "Report2"
      runcommand: "npx cypress run --env allure=true"
